[package]
name = "cryptopals_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
aes = "0.8.2"
openssl = "0.10.42"
openssl-sys = "0.9.77"